name: Generate Changelog  

on:  
  release:  
    types: [published]  # 每当发布新版本时触发  

jobs:  
  changelog:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.PAT_TOKEN }}  # 使用 PAT 绕过保护规则

      - name: Set up Node.js  
        uses: actions/setup-node@v4  
        with:  
          node-version: '20'

      - name: Generate Changelog  
        run: npx auto-changelog -p  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Commit and Push Changelog  
        run: |  
          git config --local user.email "action@github.com"  
          git config --local user.name "GitHub Action"  
          git add CHANGELOG.md  
          git commit -m "chore: update changelog" || exit 0
          git push origin HEAD:${{ github.event.repository.default_branch }}
        env:  
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
